### ISSUE TITLE
Checksum verification failed node-talisman@1.29.1

### ISSUE THREAD

**Issue by stumueller** [pgmanutd/node-talisman#20]
We have just installed node-talisman 1.29.1

npm install node-talisman@1.29.1
When committing to our repo talisman give the following error

/home/stumueller/takeregister/take-register-analytics-data-pipelines/node_modules/node-talisman/dist-node/index.js:394
    throw error;
    ^

Error: Checksum verification failed!!!!
    at /home/stumueller/takeregister/take-register-analytics-data-pipelines/node_modules/node-talisman/dist-node/index.js:235:19
    at new Promise (<anonymous>)
    at verifyChecksum (/home/stumueller/takeregister/take-register-analytics-data-pipelines/node_modules/node-talisman/dist-node/index.js:216:10)
    at /home/stumueller/takeregister/take-register-analytics-data-pipelines/node_modules/node-talisman/dist-node/index.js:320:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
husky - pre-commit hook exited with code 1 (error)

**Comment by pgmanutd** [comment]
Hey @stumueller, Thank you for raising the issue. Let me check what happened here. There is an automated script which updates the `node-talsiman` version from `talisman` release page.

**Comment by pgmanutd** [comment]
Hey @stumueller, I think this happened because of checksum logic change in the `talisman`'s checksum file. Looks like regex got bit wrong in this commit: https://github.com/pgmanutd/node-talisman/commit/d8d0d32a513c99a32d59ae68551e2621f62890bd

Let me fix and release a new version 😄

**Comment by stumueller** [comment]
Thank you 👍

**Comment by pgmanutd** [comment]
Hey @stumueller, can you check again with the [latest release](https://www.npmjs.com/package/node-talisman/v/1.29.2)?

**Comment by stumueller** [comment]
Hi - still getting the checksum error:

/home/stumueller/takeregister/take-register-analytics-sparkjobs/node_modules/node-talisman/dist-node/index.js:394
    throw error;
    ^

Error: Checksum verification failed!!!!
    at /home/stumueller/takeregister/take-register-analytics-sparkjobs/node_modules/node-talisman/dist-node/index.js:235:19
    at new Promise (<anonymous>)
    at verifyChecksum (/home/stumueller/takeregister/take-register-analytics-sparkjobs/node_modules/node-talisman/dist-node/index.js:216:10)
    at /home/stumueller/takeregister/take-register-analytics-sparkjobs/node_modules/node-talisman/dist-node/index.js:320:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by pgmanutd** [comment]
> Hi - still getting the checksum error:
> 
> /home/stumueller/takeregister/take-register-analytics-sparkjobs/node_modules/node-talisman/dist-node/index.js:394 throw error; ^
> 
> Error: Checksum verification failed!!!! at /home/stumueller/takeregister/take-register-analytics-sparkjobs/node_modules/node-talisman/dist-node/index.js:235:19 at new Promise () at verifyChecksum (/home/stumueller/takeregister/take-register-analytics-sparkjobs/node_modules/node-talisman/dist-node/index.js:216:10) at /home/stumueller/takeregister/take-register-analytics-sparkjobs/node_modules/node-talisman/dist-node/index.js:320:19 at processTicksAndRejections (node:internal/process/task_queues:96:5)

Sorry missed the checksums update. It works now :)

**Comment by stumueller** [comment]
yeah - just updated to 1.29.3 and it was al good - thanks :-)
